# Change these first
owner: greend139 # Your GitHub organization or username, where this repository lives
repo: Uptime-checks # The name of this repository

sites:
  - name: Website
    url: https://www.ccri.edu
  - name: Single Sign-on
    url: https://sts.ccri.edu/cas/login
  - name: VPN Connect2
    url: https://connect2.ccri.edu:10443
  - name: Banner
    url: https://admin.ccri.edu/applicationNavigator/actuator/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Uptime-checks
  logoUrl: https://bannerweb.ccri.edu/CCRI_Logo_White_1in.svg
  themeUrl: https://greend139.github.io/Uptime-checks/ccri.css
  name: CCRI System Status
  introTitle: "System Status & Maintenance"
  introMessage: Production Systems, **real-time** data is from our [GitHub repository](https://github.com/greend139/Uptime-checks).
  navbar:
    - title: Status
      href: /$REPO
    - title: IT Helpdesk
      href: https://ccri.edu/it/helpdesk
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "[CCRI](https://ccri.edu) - This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)"

commitMessages:
  commitAuthorName: "CCRI Upptime Bot"
  commitAuthorEmail: "itops@ccri.edu"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
